export const PERSONALFORM_SAVE_REQUEST = 'PERSONALFORM_SAVE_REQUEST'
export const PERSONALFORM_SAVE_SUCCESS = 'PERSONALFORM_SAVE_SUCCESS'
export const PERSONALFORM_SAVE_FAIL = 'PERSONALFORM_SAVE_FAIL'

export const WIVESDETAILS_SAVE_REQUEST = 'WIVESDETAILS_SAVE_REQUEST'
export const WIVESDETAILS_SAVE_SUCCESS = 'WIVESDETAILS_SAVE_SUCCESS'
export const WIVESDETAILS_SAVE_FAIL = 'WIVESDETAILS_SAVE_FAIL'

export const EXECUTOR_DETAILS_SAVE_REQUEST = 'EXECUTOR_DETAILS_SAVE_REQUEST'
export const EXECUTOR_DETAILS_SAVE_SUCCESS = 'EXECUTOR_DETAILS_SAVE_SUCCESS'
export const EXECUTOR_DETAILS_SAVE_FAIL = 'EXECUTOR_DETAILS_SAVE_FAIL'

export const CHILDREN_DETAILS_SAVE_REQUEST = 'CHILDREN_DETAILS_SAVE_REQUEST'
export const CHILDREN_DETAILS_SAVE_SUCCESS = 'CHILDREN_DETAILS_SAVE_SUCCESS'
export const CHILDREN_DETAILS_SAVE_FAIL = 'CHILDREN_DETAILS_SAVE_FAIL'

export const GUARDIAN_DETAILS_SAVE_REQUEST = 'GUARDIAN_DETAILS_SAVE_REQUEST'
export const GUARDIAN_DETAILS_SAVE_SUCCESS = 'GUARDIAN_DETAILS_SAVE_SUCCESS'
export const GUARDIAN_DETAILS_SAVE_FAIL = 'GUARDIAN_DETAILS_SAVE_FAIL'

export const DISTRIBUTION_DETAILS_SAVE_REQUEST = 'DISTRIBUTION_DETAILS_SAVE_REQUEST'
export const DISTRIBUTION_DETAILS_SAVE_SUCCESS = 'DISTRIBUTION_DETAILS_SAVE_SUCCESS'
export const DISTRIBUTION_DETAILS_SAVE_FAIL = 'DISTRIBUTION_DETAILS_SAVE_FAIL'

export const REMAINDER_DETAILS_SAVE_REQUEST = 'REMAINDER_DETAILS_SAVE_REQUEST'
export const REMAINDER_DETAILS_SAVE_SUCCESS = 'REMAINDER_DETAILS_SAVE_SUCCESS'
export const REMAINDER_DETAILS_SAVE_FAIL = 'REMAINDER_DETAILS_SAVE_FAIL'

export const PET_DETAILS_SAVE_REQUEST = 'PET_DETAILS_SAVE_REQUEST'
export const PET_DETAILS_SAVE_SUCCESS = 'PET_DETAILS_SAVE_SUCCESS'
export const PET_DETAILS_SAVE_FAIL = 'PET_DETAILS_SAVE_FAIL'

export const BURIAL_DETAILS_SAVE_REQUEST = 'BURIAL_DETAILS_SAVE_REQUEST'
export const BURIAL_DETAILS_SAVE_SUCCESS = 'BURIAL_DETAILS_SAVE_SUCCESS'
export const BURIAL_DETAILS_SAVE_FAIL = 'BURIAL_DETAILS_SAVE_FAIL'

export const ADDITIONAL_DETAILS_SAVE_REQUEST = 'ADDITIONAL_DETAILS_SAVE_REQUEST'
export const ADDITIONAL_DETAILS_SAVE_SUCCESS = 'ADDITIONAL_DETAILS_SAVE_SUCCESS'
export const ADDITIONAL_DETAILS_SAVE_FAIL = 'ADDITIONAL_DETAILS_SAVE_FAIL'

export const OTHER_DETAILS_SAVE_REQUEST = 'OTHER_DETAILS_SAVE_REQUEST'
export const OTHER_DETAILS_SAVE_SUCCESS = 'OTHER_DETAILS_SAVE_SUCCESS'
export const OTHER_DETAILS_SAVE_FAIL = 'OTHER_DETAILS_SAVE_FAIL'

export const SIGNING_DETAILS_SAVE_REQUEST = 'SIGNING_DETAILS_SAVE_REQUEST'
export const SIGNING_DETAILS_SAVE_SUCCESS = 'SIGNING_DETAILS_SAVE_SUCCESS'
export const SIGNING_DETAILS_SAVE_FAIL = 'SIGNING_DETAILS_SAVE_FAIL'

export const VALIDATION_SAVE_REQUEST = 'VALIDATION_SAVE_REQUEST'
export const VALIDATION_SAVE_SUCCESS = 'VALIDATION_SAVE_SUCCESS'
export const VALIDATION_SAVE_FAIL = 'VALIDATION_SAVE_FAIL'


export const FINAL_SAVE_REQUEST = 'FINAL_SAVE_REQUEST'
export const FINAL_SAVE_SUCCESS = 'FINAL_SAVE_SUCCESS'
export const FINAL_SAVE_FAIL = 'FINAL_SAVE_FAIL'

